const ScreenNames = {
  Otp: 'Otp',
  LoginScreen: 'LoginScreen',
  SignUpDetails: 'SignUpDetails',
  ChangePassword: 'ChangePassword',
  SignUpNumberOtp: 'SignUpNumberOtp',
  ForgotPassword: 'ForgotPassword',
  ForgotPasswordOTP: 'ForgotPasswordOTP',
  SignUpNumber: 'SignUpNumber',
  editprofile: 'EditProfile',
  addaddress: 'AddAddress',
  myratingreview: 'MyRatingReview',
  wishlist: 'Wishlist',
  catalogs: 'Catalogs',
  newdesignorproduct: 'NewDesignOrProduct',
  installationpatner: 'Installationpatner',
  cartents: 'Cartents',
  myorder: 'MyOrder',
  myorderdetails: 'MyOrderDetails',
  customheadlight: 'CustomHeadlight',
  completeorderdetails: 'CompleteOrderDetails',
  cancelledOrderDetails: 'CancelledOrderDetails',
  rating: 'Rating',
  heading: 'Heading',

  notification: 'Notification',
  dashboad: 'Dashboad',
  customisecar: 'CustomiseCar',
  wheelsVirtualizercategory: 'WheelsVirtualizerCategory',
  vehilesection: 'VehileSection',
  colorsection: 'ColorSection',
  wheelsection: 'WheelSection',
  colorsectionone: 'ColorSectionOne',
  wheelprice: 'WheelPrice',
  pricedetails: 'PriceDetails',
  thankyou: 'ThankYou',
  light: 'Light',
  cupon: 'Cupon',
  checkoutone: 'CheckOutOne',
  headlightprt: 'HeadlightPrt',
  customizeseatcover: 'CustomizeSeatCover',
  sellingcategories: 'SellingCategories',
  engineheading: 'EngineHeading',
  carproperties: 'CarProperties',
  carfacility: 'CarFacility',
  testimonials: 'Testimonials',
  myprofile: 'MyProfile',
  tabstack: 'TabStack',
  tabstack: 'TabStackNavigator',
  sidemenubar: 'SideMenuBar',
  customerupload: 'CustomerUpload',
  stories: 'Stories',
  shippingpolicy: 'ShippingPolicy',
  selectaddressone: 'SelectAddressOne',
  selectaddress: 'SelectAddress',
  drawernavigation: 'DrawerNavigation',
  filter: 'Filter',
  thankyou: 'ThankYou',
  customerupload: 'CustomerUpload',
  changepasswordone: 'ChangePasswordOne',
  otptwo: 'otptwo',
  autocare: 'AutoCare',

  productsList: 'ProductList',
  productdetails: 'ProductDetails',

  onBoardng: 'onBoarding',

  description: 'Description',
  productlightdetails: 'ProductLightDetails',
  delivery: 'Delivery',
  relatedproduct: 'RelatedProduct',
  lightdescription: 'LightDescription',
  customlights: 'CustomLights',
  customlight: 'CustomLight',
  customizeseat: 'CustomizeSeat',
  ordertrack: 'OrderTrack',
  carpropertiesone: 'CarPropertiesOne',
  Home: 'MainHome',
  logOut: 'logout',

  // ----------bottom screens---------
  dashHome: 'DashHome',
  accessories: 'Accessories',
  carts: 'carts',
  more: 'More',
  addstories: 'AddStories',

  // *************************************** Drawer ***************************

  drawerHome: 'drawerHome',

  checkout: 'CheckoutPage',

  // *************************************** Static Pages ***************************
  aboutus: 'AboutUs',
  privacypolicy: 'PrivacyPolicy',
  returnpolicy: 'ReturnPolicy',
  refundPolicy: 'RefundPolicy',
  termsAndConditions: 'TermsAndConditions',
  termsofuse: 'TermsOfUse',
  contactus: 'ContactUs',
  feedback: 'Feedback',
  purchaseGiftCard: 'PurchaseGiftCard',
  customerSupport: 'CustomerSupport',
  reward: 'Rewards',
  LoginViaProtect: 'LoginViaProtect',
  PaymentSuccessful: 'PaymentSuccessful',
  addressChange: 'addressChange',
  profileChange: 'profileChange',
};

export default ScreenNames;
